// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiPaQfJqwmI5kBQ0jp4gzowoyRP3WlXb4',
    appId: '1:503874257181:web:f029f61ce7036bc46e61f4',
    messagingSenderId: '503874257181',
    projectId: 'ecotrack-5eaa2',
    authDomain: 'ecotrack-5eaa2.firebaseapp.com',
    storageBucket: 'ecotrack-5eaa2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0gu3lNJ0MjFDzIog-sPZWc77Y194JCAw',
    appId: '1:503874257181:android:9c3190e114387b5d6e61f4',
    messagingSenderId: '503874257181',
    projectId: 'ecotrack-5eaa2',
    storageBucket: 'ecotrack-5eaa2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1nriYmsI3_SFbrZgS8Vcgo8tD-ZTyWeg',
    appId: '1:503874257181:ios:0bbc03d28fa845366e61f4',
    messagingSenderId: '503874257181',
    projectId: 'ecotrack-5eaa2',
    storageBucket: 'ecotrack-5eaa2.firebasestorage.app',
    iosBundleId: 'com.example.ecotrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1nriYmsI3_SFbrZgS8Vcgo8tD-ZTyWeg',
    appId: '1:503874257181:ios:0bbc03d28fa845366e61f4',
    messagingSenderId: '503874257181',
    projectId: 'ecotrack-5eaa2',
    storageBucket: 'ecotrack-5eaa2.firebasestorage.app',
    iosBundleId: 'com.example.ecotrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiPaQfJqwmI5kBQ0jp4gzowoyRP3WlXb4',
    appId: '1:503874257181:web:243fbe8f983240756e61f4',
    messagingSenderId: '503874257181',
    projectId: 'ecotrack-5eaa2',
    authDomain: 'ecotrack-5eaa2.firebaseapp.com',
    storageBucket: 'ecotrack-5eaa2.firebasestorage.app',
  );
}
